[book]
title = "Um Livrinho Sobre Exploit Dev"
authors = ["0xturazzi"]
language = "pt-br"
multilingual = false
src = "src"

[build]
create-missing = false

[output.html]
default-theme = "Ayu"
no-section-label = true
git-repository-url = "https://github.com/0xturazzi/Um-Livrinho-Sobre-Exploit-Dev/"
input-404 = "./aventura.md"

site-url = "/book/"
[output.html.fold]
enable = true
level = 0
