[book]
title = "Um Livrinho Sobre Exploit Dev"
authors = ["0xturazzi"]
language = "pt-br"
multilingual = false
src = "src"

[output.html]
curly-quotes = true
default-theme = "ayu"
git-repository-url = "https://github.com/0xturazzi/Um-Livrinho-Sobre-Exploit-Dev/"
site-url = "https://0xturazzi.github.io/Um-Livrinho-Sobre-Exploit-Dev/"
